-- DBMS_DDL.CREATE_WRAPPED
DECLARE
    CODIGO VARCHAR2(1000) := '
        CREATE OR REPLACE PROCEDURE PROC2
        IS
            NUM_EMPLE NUMBER;
        BEGIN
            SELECT COUNT(*) INTO NUM_EMPLE FROM EMPLOYEES;
            DBMS_OUTPUT.PUT_LINE(NUM_EMPLE);
        END;';
BEGIN
    -- ENTRE PARÉNTESIS VA EL CÓDIGO PLSQL A OFUSCAR
    DBMS_DDL.CREATE_WRAPPED(CODIGO);
END;
/
    
SELECT LINE, TEXT FROM USER_SOURCE WHERE NAME LIKE 'PROC%';