CREATE OR REPLACE PROCEDURE PROC1
IS
    NUM_EMPLE NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_EMPLE FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(NUM_EMPLE);
END;
/

-- EJEMPLOS DE OFUSCACIÓN

-- WRAP SIMPLE
-- EN EL DIRECTORIO DONDE SE ENCUENTRE EL ARCHIVO SQL, SE DEBE EJECUTAR wrap iname=<nombre_del_archivo>
-- EJEMPLO (DENTRO DE LA CARPETA S12 - OFUSCACIÓN): wrap iname=proc1.sql

-- WRAP INDICANDO EL NOMBRE DEL ARCHIVO OFUSCADO
-- EN EL DIRECTORIO DONDE SE ENCUENTRE EL ARCHIVO SQL, SE DEBE EJECUTAR wrap iname=<nombre_del_archivo_base> oname=<nombre_del_archivo_deseado_para_el_contenido_ofuscado>
-- EJEMPLO (DENTRO DE LA CARPETA S12 - OFUSCACIÓN): wrap iname=proc1.sql oname=proc1_ofus

-- SE PUEDE COMPILAR CÓDIGO OFUSCADO EN LA BASE DE DATOS. LO ENTIENDE PERFECTAMENTE
