SET SERVEROUTPUT ON
EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR('ALBERTO', 'PÉREZ'));
EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR(10, 30));
EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR(SYSDATE, 1));