-- SOBRECARGA: FUNCIONES CON EL MISMO NOMBRE PERO CON DISTINTOS ARGUMENTOS (EN NÚMERO O EN TIPO).
-- CONDICIONES PARA LA SOBRECARGA
-- * NÚMERO DE ARGUMENTOS DISTINTO ENTRE FUNCIONES
-- * MISMA CANTIDAD DE ARGUMENTOS PERO DISTINTOS TIPOS DE DATOS

CREATE OR REPLACE PACKAGE SOBRECARGA AS
    FUNCTION CONCATENAR (A VARCHAR2, B VARCHAR2) RETURN VARCHAR2;
    FUNCTION CONCATENAR (A NUMBER, B NUMBER) RETURN NUMBER;
    FUNCTION CONCATENAR (A DATE, B NUMBER) RETURN DATE;
END SOBRECARGA;
/

CREATE OR REPLACE PACKAGE BODY SOBRECARGA AS
    FUNCTION CONCATENAR (A VARCHAR2, B VARCHAR2) RETURN VARCHAR2
    IS
        BEGIN
            RETURN A || ' ' || B;       
        END;
        
    FUNCTION CONCATENAR (A NUMBER, B NUMBER) RETURN NUMBER
    IS
        BEGIN
            RETURN A + B;       
        END;
    
    FUNCTION CONCATENAR (A DATE, B NUMBER) RETURN DATE
    IS
        BEGIN
            RETURN A + B;       
        END;
    
END SOBRECARGA;
/
    