-- SE CREA EL TRIGGER MEDIANTE UNA CONEXIÓN CON SYSTEM
-- ESTE TRIGGER SE DISPARA PARA CUALQUIER OBJETO DE TODA LA BASE DE DATOS
CREATE OR REPLACE TRIGGER BORRAR_OBJETO
AFTER DROP
ON DATABASE
BEGIN
    INSERT INTO HR.CONTROL_LOG (EVENTO) VALUES ('HEMOS BORRADO UN OBJETO A NIVEL DE DATABASE LLAMADO ' || ORA_DICT_OBJ_NAME || ' DE TIPO ' || ORA_DICT_OBJ_TYPE || ' QUE PERTENECE AL USUARIO ' || ORA_DICT_OBJ_OWNER);
END;
/