CREATE TABLE CONTROL_LOGINS
(
    USUARIO VARCHAR2(100),
    IP VARCHAR2(100),
    FECHA DATE
);
/

/*
    ATRIBUTOS PARA TRIGGERS DE TIPO LOGIN
    
    - ORA_SYSEVENT
    - ORA_LOGIN_USER
    - ORA_INSTANCE_NUM
    - ORA_DATABASE_NAME
    - ORA_CLIENT_IP_ADDRESS
*/


CREATE OR REPLACE TRIGGER LOGIN
AFTER LOGON
ON DATABASE
BEGIN
    INSERT INTO CONTROL_LOGINS VALUES (ORA_LOGIN_USER, ORA_CLIENT_IP_ADDRESS, SYSDATE);
END;
/

SELECT * FROM CONTROL_LOGINS;
