CREATE TABLE CONTROL_ERRORES
(
    USUARIO VARCHAR2(100),
    MENSAJE_ERROR VARCHAR2(100),
    COMANDO_SQL VARCHAR2(1000),
    FECHA DATE
);
/

/*
    ATRIBUTOS PARA LOS TRIGGERS DE ERRORES
    - ORA_NAME_LIST_T --> IS TABLE OF VARCHAR2(64)
    - ORA_SYSEVENT
    - ORA_LOGIN_USER
    - ORA_INSTANCE_NUM
    - ORA_DATABASE_NAME
    - ORA_SERVER_ERROR
        -- ORA_SERVER_ERROR_DEPTH
        -- ORA_SERVER_ERROR_MSG (POSITION IN BINARY_INTEGER PARA OBTENER EL MENSAJE DE ERROR EN CASO QUE SE HAYAN GENERADO MÚLTIPLES ERRORES)
    - ORA_SQL_TXT (SQL_TEXT OUT ORA_NAME_LIST_T)
    - ORA_IS_SERVER_ERROR
    - ORA_SPACE_ERROR_INFO
*/

CREATE OR REPLACE TRIGGER CAPTURAR_ERRORES
AFTER SERVERERROR
ON DATABASE
DECLARE
    SQL_TEXT ORA_NAME_LIST_T;
    MENSAJE VARCHAR2(2000) := NULL;
    COMANDO VARCHAR2(200) := NULL;
BEGIN
    FOR X IN 1..ORA_SERVER_ERROR_DEPTH LOOP
        MENSAJE := MENSAJE || ORA_SERVER_ERROR_MSG(X);
    END LOOP;
    
    FOR I IN 1..ORA_SQL_TXT(SQL_TEXT) LOOP
        COMANDO := COMANDO || SQL_TEXT(I);
    END LOOP;
    
    INSERT INTO CONTROL_ERRORES VALUES (ORA_LOGIN_USER, MENSAJE, COMANDO, SYSDATE);
END;
/

SELECT * FROM XXXXX;

SELECT * FROM CONTROL_ERRORES;
