SET SERVEROUTPUT ON;

DECLARE
    -- LOS CURSORES SON COMO PUNTEROS A UNA ZONA ESPECÍFICA DE MEMORIA
    TYPE CURSOR_VARIABLE IS REF CURSOR RETURN EMPLOYEES%ROWTYPE;
    V1 CURSOR_VARIABLE;
    V2 CURSOR_VARIABLE;
    EMPLEADOS EMPLOYEES%ROWTYPE;
BEGIN
    -- ABRIMOS EL CURSOR CON LA PRIMERA VARIABLE
    OPEN V1 FOR SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME;
    FETCH V1 INTO EMPLEADOS; -- RETORNA EL EMPLEADO 1
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME|| ' ' ||EMPLEADOS.SALARY);
    
    -- ASIGNAMOS V1 A V2
    V2 := V1; -- RETORNA EL EMPLEADO 2
    FETCH V2 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME|| ' ' ||EMPLEADOS.SALARY);
    
    FETCH V1 INTO EMPLEADOS; -- RETORNA EL EMPLEADO 3
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME|| ' ' ||EMPLEADOS.SALARY);
    
    CLOSE V1;
END;