CREATE OR REPLACE PACKAGE PACK1
AS
    TYPE C_VARIABLE IS REF CURSOR; -- CURSOR GENÉRICO
    -- EL REF CURSOR DEBEN SER IN OUT OBLIGATORIAMENTE
    FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE, X NUMBER) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PACK1 AS
    FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE, X NUMBER) RETURN VARCHAR2
    IS
        DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
        EMPLEADOS EMPLOYEES%ROWTYPE;
    BEGIN
        IF X = 1 THEN
            OPEN C1 FOR SELECT * FROM EMPLOYEES;
            FETCH C1 INTO EMPLEADOS;
            RETURN EMPLEADOS.FIRST_NAME;
        ELSE
            OPEN C1 FOR SELECT * FROM DEPARTMENTS;
            FETCH C1 INTO DEPARTAMENTOS;
            RETURN DEPARTAMENTOS.DEPARTMENT_NAME;
        END IF;
    END;
END;
/

SET SERVEROUTPUT ON;
DECLARE
    -- DEBE HACER REFERENCIA AL TIPO DE CURSOR DEFINIDO EN EL PAQUETE
    DATOS PACK1.C_VARIABLE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(PACK1.DEVOLVER_DATOS(DATOS, 1));
END;

