-- PRÁCTICA 20: REF CURSORS Y TIPOS
SET SERVEROUTPUT ON;
DECLARE
    -- EL CURSOR ES DE TIPO DEPARTMENTS, TIENE UN TIPO DEFINIDO
    TYPE C1 IS REF CURSOR RETURN DEPARTMENTS%ROWTYPE;
    V1 C1;
    DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
    OPEN V1 FOR SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID > 150;
    FETCH V1 INTO DEPARTAMENTOS;
    WHILE V1%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
        FETCH V1 INTO DEPARTAMENTOS;
    END LOOP;
    CLOSE V1;
END;