SET SERVEROUTPUT ON

-- SYS_REFCURSOR

DECLARE
    --TYPE CURSOR_VARIABLE IS REF CURSOR;
    --V1 CURSOR_VARIABLE;
    V1 SYS_REFCURSOR; -- ES EQUIVALENTE A LO DEFINIDO ARRIBA. SE PUEDE USAR CUANDO EL REF CURSOR NO TENGA UN RETURN
    
    DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
    
    OPEN V1 FOR SELECT * FROM DEPARTMENTS;
    FETCH V1 INTO DEPARTAMENTOS;
    WHILE V1%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
        FETCH V1 INTO DEPARTAMENTOS;
    END LOOP;
    
    CLOSE V1;
END;