SET SERVEROUTPUT ON
DECLARE
    X   CONSTANT NUMBER := 100;
    Z   NUMBER NOT NULL := 20;
    B1  BOOLEAN;
BEGIN
    Z := 30;
    B1 := TRUE;
    B1 := FALSE;
    B1 := NULL;
    
    DBMS_OUTPUT.PUT_LINE(X);
    DBMS_OUTPUT.PUT_LINE(Z);
END;