SET SERVEROUTPUT ON
DECLARE
    NAME VARCHAR2(100);
    LASTNAME VARCHAR2(100);
BEGIN
    NAME := 'Andrea';
    LASTNAME := 'Da Silva';
    DBMS_OUTPUT.PUT_LINE(100);
    DBMS_OUTPUT.PUT_LINE('Los quiero - '||NAME||' '||LASTNAME);
END;