SET SERVEROUTPUT ON;

DECLARE
    
    TYPE SUM_SALARIOS IS RECORD 
        (
            NOMBRE DEPARTMENTS.DEPARTMENT_NAME%TYPE,
            SUMA_SALARIOS NUMBER
        );
    
    TYPE SUMA_SAL IS TABLE OF SUM_SALARIOS INDEX BY PLS_INTEGER;
    
    SALARIOS SUMA_SAL;
    
BEGIN

    SELECT DEPARTMENT_NAME, SUM(SALARY)
    BULK COLLECT INTO SALARIOS
    FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
    GROUP BY DEPARTMENT_NAME; -- LA CLAVE DE SALARIOS NO ES EL ID DEL REGISTRO, ES LA POSICIÓN DEL REGISTRO POSTERIOR A LA EJECUCIÓN DEL QUERY
    
    
    FOR I IN 1..SALARIOS.COUNT() LOOP
        DBMS_OUTPUT.PUT_LINE(SALARIOS(I).NOMBRE || ' ' || SALARIOS(I).SUMA_SALARIOS);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('NÚMERO DE FILAS ' || SALARIOS.COUNT());
    DBMS_OUTPUT.PUT_LINE('PRIMER REGISTRO ' || SALARIOS.FIRST());
    DBMS_OUTPUT.PUT_LINE('ÚLTIMO REGISTRO ' || SALARIOS.LAST());
    
    DBMS_OUTPUT.PUT_LINE('');
    
    IF (SALARIOS.EXISTS(20)) THEN -- PREGUNTA SI EXISTE UN ELEMENTO CON LA CLAVE INDICADA
        DBMS_OUTPUT.PUT_LINE('EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('');
    
    SALARIOS.DELETE(1);
    
    DBMS_OUTPUT.PUT_LINE('PRIMER REGISTRO ' || SALARIOS.FIRST());
    DBMS_OUTPUT.PUT_LINE('REGISTRO ANTERIOR AL 3: ' || SALARIOS.PRIOR(3));
    DBMS_OUTPUT.PUT_LINE('REGISTRO SIGUIENTE DE 3: ' || SALARIOS.NEXT(3));

END;