SET SERVEROUTPUT ON;

DECLARE 
    TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE
        INDEX BY PLS_INTEGER;
        
    DEPTS DEPARTAMENTOS;
    CURSOR CUR_DEPT IS SELECT * FROM DEPARTMENTS;
    X PLS_INTEGER := 1;
    
    TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
    CURSOR CUR_EMP IS SELECT * FROM EMPLOYEES WHERE SALARY > 5000;
    Z PLS_INTEGER := 1;
    
    EMPLES EMPLEADOS;
    
    TYPE NOMBRE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY VARCHAR2(2);
    
    NOMBRES NOMBRE;
BEGIN
    
    FOR DEPT1 IN CUR_DEPT LOOP
        DEPTS(X) := DEPT1.DEPARTMENT_NAME;
        X := X + 1;
    END LOOP;
    
    FOR I IN 1..X-1 LOOP
        DBMS_OUTPUT.PUT_LINE(DEPTS(I));
    END LOOP;
    
    
    
    FOR EMP1 IN CUR_EMP LOOP
        EMPLES(Z) := EMP1;
        Z := Z + 1;
    END LOOP;
    
    FOR I IN 1..Z-1 LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLES(I).FIRST_NAME || ' ' || EMPLES(I).SALARY);
    END LOOP;
END;
/