SET SERVEROUTPUT ON;

DECLARE 
    TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE INDEX BY PLS_INTEGER;
    DEPTS DEPARTAMENTOS;
    CURSOR CUR_DEPT IS SELECT * FROM DEPARTMENTS;
    
    
    TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
    EMPLES EMPLEADOS;
    
BEGIN
    
    SELECT *
    BULK COLLECT INTO EMPLES -- ES ÓPTIMO USAR BULK COLLECT EN VEZ DE UN CURSOR EN UN BUCLE
    FROM EMPLOYEES WHERE SALARY > 5000;
    
    FOR I IN 1..EMPLES.COUNT() LOOP -- BULK COLLECT EMPIEZA EN 1. SIEMPRE EMPEZAR EL FOR DESDE 1 E INCREMENTARLO DE 1 EN 1
        DBMS_OUTPUT.PUT_LINE(EMPLES(I).FIRST_NAME || ' ' || EMPLES(I).SALARY);
    END LOOP;
END;
/