/*  

            MÉTODOS DE COLECCIONES
            
    1. DELETE (PROCEDURE): ELIMINA ELEMENTOS DE UNA TABLA ANIDADA O TABLA INDEXADA
    2. TRIM (PROCEDURE): ELIMINA ELEMENTOS DESDE EL FINAL DE UN VARRAY O TABLA ANIDADA
    3. EXTEND (PROCEDURE): AGREGA ELEMENTOS AL FINAL DE UN VARRAY O TABLA ANIDADA
    4. EXISTS (FUNCTION): RETORNA TRUE SI Y SOLO SI EXISTE EL ELEMENTO ESPECIFICADO EN LA COLECCIÓN
    5. FIRST (FUNCTION): RETORNA EL PRIMER ÍNDICE DE LA COLECCIÓN
    6. LAST (FUNCTION): RETORNA EL ÚLTIMO ÍNDICE DE LA COLECCIÓN
    7. COUNT (FUNCTION): RETORNA EL NÚMERO DE ELEMENTOS DE LA COLECCIÓN
    8. LIMIT (FUNCTION): RETORNA EL NÚMERO MÁXIMO DE ELEMENTOS QUE UNA COLECCIÓN PUEDA TENER
    9. PRIOR (FUNCTION): RETORNA EL ÍNDICE QUE PRECEDE AL ÍNDICE ESPECIFICADO
    10. NEXT (FUNCTION): RETORNA EL ÍNDICE SIGUIENTE AL ÍNDICE ESPECIFICADO

*/