CREATE OR REPLACE TYPE OBJETO_REGIONES IS OBJECT
(
    REGION_ID NUMBER,
    REGION_NAME VARCHAR2(25)
);
/

CREATE OR REPLACE TYPE NESTED_REGIONES IS TABLE OF OBJETO_REGIONES;
/

CREATE TABLE N_REGIONES
(
    CODIGO NUMBER,
    REGIONES NESTED_REGIONES
)
NESTED TABLE REGIONES STORE AS TABLA_REGIONES;
/

-- CREATE OR REPLACE TYPE NESTED_REGIONES IS TABLE OF REGIONS%ROWTYPE; -- ESTO ES UN TIPO DE DATO PLSQL. SOLO SE PUEDE USAR SQL. ROWTYPE ES PLSQL

