CREATE OR REPLACE TYPE EMPLEADO IS TABLE OF VARCHAR2(100);
/

SET SERVEROUTPUT ON;

DECLARE
    EMPLEADOS EMPLEADO;
BEGIN
    EMPLEADOS := EMPLEADO('SERGIO', 'ALBERTO', 'ROSA');
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS(1));
END;
/