-- NESTED TABLES
SET SERVEROUTPUT ON;

DECLARE
    -- NO TIENEN LÍMITE DEFINIDO. PUEDEN ENTRAR CUANTOS ELEMENTOS DESEEN
    -- LOS ELEMENTOS PUEDEN ESTAR DISPERSOS, ES DECIR, LOS ELEMENTOS NO NECESARIAMENTE DEBEN SER CONTIGUOS
    -- SE ACCEDEN POR POSICIÓN NO POR CLAVE
    TYPE EMPLEADO IS TABLE OF EMPLOYEES%ROWTYPE;
    EMPLEADOS EMPLEADO := EMPLEADO(); -- SE INICIALIZA CON EL CONSTRUCTOR
BEGIN

    -- BULK COLLECT
    SELECT * BULK COLLECT
    INTO EMPLEADOS
    FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;
    
    FOR I IN EMPLEADOS.FIRST..EMPLEADOS.LAST LOOP -- EMPLEADOS.FIRST ES IGUAL A EMPLEADOS.FIRST()
        DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME || ' ' || EMPLEADOS(I).SALARY);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('');
    
    DBMS_OUTPUT.PUT_LINE('PRIMER ELEMENTO: ' || EMPLEADOS.FIRST);
    DBMS_OUTPUT.PUT_LINE('ÚLTIMO ELEMENTO: ' || EMPLEADOS.LAST);
    DBMS_OUTPUT.PUT_LINE('SIGUIENTE ELEMENTO: ' || EMPLEADOS.NEXT(1));
    
    DBMS_OUTPUT.PUT_LINE('');
    
    IF (EMPLEADOS.EXISTS(20)) THEN
        DBMS_OUTPUT.PUT_LINE('EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;
    
    EMPLEADOS.DELETE(2);
    
    DBMS_OUTPUT.PUT_LINE('');
    
    FOR I IN EMPLEADOS.FIRST..EMPLEADOS.LAST LOOP -- DA ERROR EN LA POSICIÓN 2 YA QUE, EL ELEMENTO FUE ELIMINADO
        IF (EMPLEADOS.EXISTS(I)) THEN -- SE DEBE VALIDAR QUE LOS ELEMENTOS EXISTAN
            DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME || ' ' || EMPLEADOS(I).SALARY);
        END IF;
    END LOOP;
    
END;
/