SET SERVEROUTPUT ON;

DECLARE
    TYPE EMPLEADO IS VARRAY(10) OF EMPLOYEES%ROWTYPE;
    
    CURSOR C1 IS SELECT * FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;
    CONTADOR NUMBER := 1;
    
    EMPLEADOS EMPLEADO := EMPLEADO(); -- SE INICIALIZA CON EL CONSTRUCTOR
BEGIN

    -- BULK COLLECT
    /*SELECT * BULK COLLECT
    INTO EMPLEADOS
    FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;
    -- NO ES NECESARIO EXTENDER EL VARRAY, EL BULK COLLECT LO HACE AUTOMÁTICAMENTE
    
    FOR I IN EMPLEADOS.FIRST..EMPLEADOS.LAST LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME || ' ' || EMPLEADOS(I).LAST_NAME);
    END LOOP;*/
    
    
    DBMS_OUTPUT.PUT_LINE('');
    
    
    -- CURSORES
    FOR X IN C1 LOOP
        EMPLEADOS.EXTEND(1);
        EMPLEADOS(CONTADOR) := X;
        CONTADOR := CONTADOR + 1;
    END LOOP;
    
    FOR I IN EMPLEADOS.FIRST..EMPLEADOS.LAST LOOP -- EMPLEADOS.FIRST ES IGUAL A EMPLEADOS.FIRST()
        DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME || ' ' || EMPLEADOS(I).LAST_NAME);
    END LOOP;

END;
/