
-- PRÁCTCA 11: COMPILAR PAQUETES INVÁLIDOS

CREATE OR REPLACE PACKAGE PACK1 IS
    FUNCTION F1 RETURN NUMBER;
    PROCEDURE P1;
END;
/

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%PACK1%'; -- HAY DOS OBJETOS PACK1: LA CABECERA Y EL BODY

CREATE OR REPLACE PACKAGE BODY PACK1 IS
    FUNCTION F1 RETURN NUMBER
    IS
    BEGIN
        RETURN 0;
    END;
    
    PROCEDURE P1
    IS
    BEGIN
        NULL;
    END;
END;
/

-- SIEMPRE QUE SE MODIFICA LA CABECERA DE UN PAQUETE, SE VE AFECTADO EL BODY. DE FORMA CONTRARIA, ESO NO OCURRE.

CREATE OR REPLACE PACKAGE PACK1 IS
    FUNCTION F1 RETURN NUMBER;
    PROCEDURE P1;
    PROCEDURE P2;
END;
/

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%PACK1%'; -- EL BODY DEL PAQUETE ES INVÁLIDO

CREATE OR REPLACE PACKAGE BODY PACK1 IS
    FUNCTION F1 RETURN NUMBER
    IS
    BEGIN
        RETURN 0;
    END;
    
    PROCEDURE P1
    IS
    BEGIN
        NULL;
    END;
    
    PROCEDURE P2
    IS
    BEGIN
        NULL;
    END;
    
    -- SE AGREGA OTRO PROCEDIMIENTO AL BODY Y SE VALIDA QUE NO AFECTA EL STATUS DEL PACK1 (TANTO CABECERA COMO BODY)
    PROCEDURE P3
    IS
    BEGIN
        NULL;
    END;
END;
/

SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%PACK1%'; -- EL BODY DEL PAQUETE Y LA CABECERA SON VÁLIDOS

-- PARA COMPILAR LOS PAQUETES, TANTO CABECERA COMO BODY

ALTER PACKAGE PACK1 COMPILE;
ALTER PACKAGE PACK1 COMPILE BODY;