--EXECUTE IMMEDIATE COMANDO
--INTO V1, V2, V3 USING ARG1, ARG2;

CREATE OR REPLACE FUNCTION NUM_EMPLE (DEPARTAMENTO_NUM NUMBER)
RETURN NUMBER
IS
    COMANDO VARCHAR2(200);
    NUM_EMPLEADOS NUMBER;
BEGIN
    COMANDO := 'SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = :DEPARTAMENTO'; -- BIND VARIABLE
    EXECUTE IMMEDIATE COMANDO INTO NUM_EMPLEADOS USING DEPARTAMENTO_NUM; 
    -- EL RESULTADO DEL SELECT SE GUARDA EN LA VARIABLE INTO
    -- LAS CONDICIONES O LAS VARIABLES DE TIPO BIND SE COLOCAN EN USING
    RETURN NUM_EMPLEADOS;
END;
/


DECLARE 
    DEPART NUMBER;
    EMPLE NUMBER;
BEGIN
    DEPART := 10;
    EMPLE := NUM_EMPLE(DEPART);
    DBMS_OUTPUT.PUT_LINE('HAY ' || EMPLE || ' EMPLEADOS EN EL DEPARTAMENTO ' || DEPART);
END;
