-- BULK COLLECT
-- OPEN - FETCH - CLOSE

DECLARE
    TYPE EMPLE_TYPE IS RECORD (
        NOMBRE_COMPLETO VARCHAR2(100),
        SALARIO NUMBER,
        IMPUESTOS NUMBER
    );
    
    TYPE EMPLEADO IS TABLE OF EMPLE_TYPE INDEX BY PLS_INTEGER;
    
    EMPLEADOS EMPLEADO;
    
    CONDICION NUMBER;
    
    COMANDO VARCHAR2(1000);
BEGIN
    CONDICION := 5000;
    COMANDO := q'[SELECT FIRST_NAME ||' '|| LAST_NAME, SALARY, SALARY*15/100 FROM EMPLOYEES
                WHERE SALARY > :CONDICION ORDER BY SALARY DESC]'; -- SE COLOCA LA q'[query] PARA USAR LAS COMILLAS CORRECTAMENTE
    
    EXECUTE IMMEDIATE COMANDO BULK COLLECT INTO EMPLEADOS USING CONDICION;
    
    FOR X IN 1..EMPLEADOS.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLEADOS(X).NOMBRE_COMPLETO || ' ' || EMPLEADOS(X).SALARIO || ' ' || EMPLEADOS(X).IMPUESTOS);
    END LOOP;
END;
/