-- EXECUTE IMMEDIATE cadena
/*
    CREATE TABLE NOM (V1 NUMBER, V2 VARCHAR2(200));
*/
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE CREAR_TABLA (NOMBRE_TABLA VARCHAR2, COLUMNAS VARCHAR2)
AUTHID CURRENT_USER -- DEFINER (SE EJECUTA COMO EL USUARIO QUE CREÓ EL PROCEDIMIENTO) | CURRENT_USER (SE EJECUTA COMO EL USUARIO ACTUAL)
IS
    COMANDO VARCHAR2(100);
BEGIN
    COMANDO := 'CREATE TABLE ' || NOMBRE_TABLA || '(' || COLUMNAS || ')';
    DBMS_OUTPUT.PUT_LINE(COMANDO);
    EXECUTE IMMEDIATE COMANDO;
END;
/


BEGIN
    CREAR_TABLA('PRU3', 'CODIGO NUMBER, DATOS VARCHAR2(100)');
END;
/
