-- SELECT
-- DBMS_SQL.DEFINE_COLUMN --> QUE COLUMNAS DE LA TABLA SE VAN A AGARRAR
-- DBMS_SQL.COLUMN_VALUE --> PERMITE OBTENER EL VALOR DE LA COLUMNA
-- DBMS_SQL.FETCH --> PERMITE CREAR UN SQL DINÁMICO EN UN SELECT

CREATE OR REPLACE PROCEDURE BUSCAR_EMPLEADOS (SALARIO NUMBER)
IS
    ID_CURSOR INTEGER;
    NUM_FILAS INTEGER;
    NOMBRE VARCHAR2(50);
    APELLIDO VARCHAR2(100);
BEGIN
    ID_CURSOR := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(ID_CURSOR, 'SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE SALARY > :SALARIO', DBMS_SQL.NATIVE);
    
    DBMS_SQL.DEFINE_COLUMN(ID_CURSOR, 1, NOMBRE, 20); -- CURSOR, POSICIÓN DE LA COLUMNA QUE DESEO RECUPERAR, TIPO DE COLUMNA QUE ESPERO RECIBIR, TAMAÑO DE LA COLUMNA QUE ESPERO RECIBIR
    DBMS_SQL.DEFINE_COLUMN(ID_CURSOR, 2, APELLIDO, 20); -- CURSOR, POSICIÓN DE LA COLUMNA QUE DESEO RECUPERAR, TIPO DE COLUMNA QUE ESPERO RECIBIR, TAMAÑO DE LA COLUMNA QUE ESPERO RECIBIR
    DBMS_SQL.BIND_VARIABLE(ID_CURSOR, ':SALARIO', SALARIO);
    
    NUM_FILAS := DBMS_SQL.EXECUTE(ID_CURSOR);
    
    LOOP    
        IF DBMS_SQL.FETCH_ROWS(ID_CURSOR) = 0 THEN -- RECUPERA LAS FILAS DEL CURSOR
            EXIT;
        END IF;
        
        DBMS_SQL.COLUMN_VALUE(ID_CURSOR, 1, NOMBRE); -- EL VALOR DE LA COLUMNA 1 DEL CURSOR LA VOY A ASOCIAR A LA VARIABLE NOMBRE
        DBMS_SQL.COLUMN_VALUE(ID_CURSOR, 2, APELLIDO); -- EL VALOR DE LA COLUMNA 1 DEL CURSOR LA VOY A ASOCIAR A LA VARIABLE NOMBRE
        DBMS_OUTPUT.PUT_LINE(NOMBRE || ' ' || APELLIDO);
    END LOOP;
    
    DBMS_SQL.CLOSE_CURSOR(ID_CURSOR);
END;
/

BEGIN
    BUSCAR_EMPLEADOS(5000);
END;
/

