-- SELECT
-- DBMS_SQL.DEFINE_COLUMN --> QUE COLUMNAS DE LA TABLA SE VAN A AGARRAR
-- DBMS_SQL.COLUMN_VALUE --> PERMITE OBTENER EL VALOR DE LA COLUMNA
-- DBMS_SQL.FETCH --> PERMITE CREAR UN SQL DINÁMICO EN UN SELECT

CREATE OR REPLACE FUNCTION BUSCAR_EMPLEADO (CODIGO NUMBER)
RETURN VARCHAR2
IS
    ID_CURSOR INTEGER;
    NUM_FILAS INTEGER;
    NOMBRE VARCHAR2(50);
BEGIN
    ID_CURSOR := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(ID_CURSOR, 'SELECT FIRST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = :COD', DBMS_SQL.NATIVE);
    
    DBMS_SQL.DEFINE_COLUMN(ID_CURSOR, 1, NOMBRE, 30); -- CURSOR, POSICIÓN DE LA COLUMNA QUE DESEO RECUPERAR, TIPO DE COLUMNA QUE ESPERO RECIBIR, TAMAÑO DE LA COLUMNA QUE ESPERO RECIBIR
    DBMS_SQL.BIND_VARIABLE(ID_CURSOR, ':COD', CODIGO);
    
    NUM_FILAS := DBMS_SQL.EXECUTE(ID_CURSOR);
    
    IF DBMS_SQL.FETCH_ROWS(ID_CURSOR) = 0 THEN -- RECUPERA LAS FILAS DEL CURSOR
        RETURN 'NO EXISTE EL EMPLEADO';
    END IF;
    
    DBMS_SQL.COLUMN_VALUE(ID_CURSOR, 1, NOMBRE); -- EL VALOR DE LA COLUMNA 1 DEL CURSOR LA VOY A ASOCIAR A LA VARIABLE NOMBRE
    DBMS_SQL.CLOSE_CURSOR(ID_CURSOR);
    RETURN NOMBRE;
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(BUSCAR_EMPLEADO(100));
END;
/

