SET SERVEROUTPUT ON
BEGIN
    UPDATE COUNTRIES SET COUNTRY_ID = 'AR' WHERE COUNTRY_NAME = 'Argentina';
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    
    IF SQL%FOUND THEN
       DBMS_OUTPUT.PUT_LINE('ENCONTRADO'); 
    END IF;
    IF SQL%NOTFOUND THEN
       DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO'); 
    END IF;
END;
SET SERVEROUTPUT ON
BEGIN
    UPDATE COUNTRIES SET COUNTRY_ID = 'AR' WHERE COUNTRY_NAME = 'Argentina';
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    
    IF SQL%FOUND THEN
       DBMS_OUTPUT.PUT_LINE('ENCONTRADO'); 
    END IF;
    IF SQL%NOTFOUND THEN
       DBMS_OUTPUT.PUT_LINE('NO ENCONTRADO'); 
    END IF;
END;