-- LAS TABLAS DE TRAZAS PERTENECEN A SYS
-- TRACETAB.SQL     RDBMS

CREATE OR REPLACE PROCEDURE PROC1
IS
    V NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V);
    SELECT COUNT(*) INTO V FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(V);
END;
/

ALTER PROCEDURE PROC1 COMPILE DEBUG; -- SE MODIFICA EL PROCEDIMIENTO PARA QUE SEA DEPURABLE

SELECT * FROM USER_PLSQL_OBJECT_SETTINGS WHERE NAME = 'PROC1';

ALTER PROCEDURE PROC1 COMPILE; -- ELIMINA LA OPCIÓN DEBUG

-- PROBANDO LAS TRAZAS

-- SE MODIFICA EL PROCEDIMIENTO PARA QUE SEA DEPURABLE
ALTER PROCEDURE PROC1 COMPILE DEBUG;

-- CON EL + SE PUEDEN COLOCAR LAS TRAZAS ADICIONALES
EXECUTE DBMS_TRACE.SET_PLSQL_TRACE(DBMS_TRACE.TRACE_ENABLED_SQL + DBMS_TRACE.TRACE_ALL_CALLS); 

EXECUTE PROC1;

-- DETIENE EL REGISTRO DE TRAZAS EN LAS TABLAS TRACE_RUNS Y TRACE_EVENTS
EXECUTE DBMS_TRACE.CLEAR_PLSQL_TRACE;

SELECT * FROM SYSTEM.PLSQL_TRACE_RUNS;
SELECT * FROM SYSTEM.PLSQL_TRACE_EVENTS;


