ALTER SESSION SET PLSQL_CODE_TYPE = 'INTERPRETED';
/

CREATE OR REPLACE PROCEDURE EJEMPLO AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('EJEMPLO');
END;
/

SELECT * FROM USER_PLSQL_OBJECT_SETTINGS WHERE NAME = 'EJEMPLO'; -- PERMITE CONOCER EL TIPO EN EL QUE FUE COMPILADO EL PROCEDIMIENTO Y EL NIVEL DE OPTIMIZACIÓN

ALTER SESSION SET PLSQL_CODE_TYPE = 'NATIVE'; -- ALTERA LA SESIÓN A MODO NATIVO
/
