-- PRÁCTICA 12: UTLDTREE VER LA JERARQUÍA DE LAS DEPENDENCIAS

DESC USER_OBJECTS;
SELECT * FROM USER_DEPENDENCIES WHERE REFERENCED_NAME = 'PRUEBA';

CREATE OR REPLACE PROCEDURE PRUEBA_P
IS
    X NUMBER;
BEGIN
    SELECT COUNT(*) INTO X FROM PRUEBA_V;
END;
/

SELECT * FROM USER_DEPENDENCIES WHERE REFERENCED_NAME = 'PRUEBA_V'; -- EL PROCEDIMIENTO PRUEBA_P DEPENDE DE PRUEBA_V

/*
    LLENA LA TABLA DEP_TREE CON LA JERARQUÍA DE LAS DEPENDENCIAS DONDE SE ESPECIFICA EL TIPO DE OBJETO (TABLE),
    EL USUARIO QUE LO CREÓ (HR) Y EL NOMBRE DEL OBJETO (PRUEBA)
*/
EXECUTE DEPTREE_FILL('TABLE', 'HR', 'PRUEBA');
SELECT * FROM DEP_TREE; -- MUESTRA LA JERARQUÍA DONDE LA TABLA PRUEBA ES LA RAÍZ DE LA JERARQUÍA
-- NESTED_LEVEL | TYPE | NAME
-- 0    | TABLE     | PRUEBA
-- 1    | VIEW      | PRUEBA_V
-- 2    | PROCEDURE | PRUEBA_P




