-- NO SE PUEDEN ABRIR LOBS DE TIPO BFILE PARA ESCRITURA

CREATE TABLE PRUEBA_LOB1 (EMPLEADO CLOB);
/

SELECT * FROM CLIENTES;

CREATE OR REPLACE PROCEDURE CARGA_EMPLE
IS
    CURSOR CLI IS SELECT * FROM EMPLOYEES;
    TEMPORAL CLOB;
    CANTIDAD INTEGER;
    NOMBRE VARCHAR2(100);
BEGIN
    FOR C1 IN CLI LOOP
        DBMS_LOB.CREATETEMPORARY(TEMPORAL, TRUE);
        
        DBMS_LOB.OPEN(TEMPORAL, DBMS_LOB.LOB_READWRITE);
        
        NOMBRE := C1.FIRST_NAME || ' ' || C1.LAST_NAME;
        
        CANTIDAD := LENGTH(NOMBRE);
        
        DBMS_LOB.WRITE(TEMPORAL, CANTIDAD, 1, NOMBRE);
        
        INSERT INTO PRUEBA_LOB1 VALUES (TEMPORAL);
        
        DBMS_LOB.CLOSE(TEMPORAL);
    END LOOP;
END;
/

EXECUTE CARGA_EMPLE;

SELECT * FROM PRUEBA_LOB1;
