SELECT * FROM CLIENTES;

CREATE OR REPLACE PROCEDURE CARGA_CLIENTES
AS
    CURSOR CLI IS SELECT * FROM CLIENTES FOR UPDATE;
    FICHERO VARCHAR2(100);
BEGIN
    FOR C1 IN CLI LOOP
        FICHERO := 'cliente' || C1.CODIGO || '.png';
        UPDATE CLIENTES SET FOTO = BFILENAME('FICHEROS', FICHERO), TAM = TAM('FICHEROS', C1.CODIGO) WHERE CURRENT OF CLI;
    END LOOP;
END;
/

EXECUTE CARGA_CLIENTES;