DECLARE
    FOTO BFILE;
BEGIN
    FOTO := BFILENAME('FICHEROS', 'cliente1.png');
    DBMS_LOB.OPEN(FOTO, DBMS_LOB.LOB_READONLY);
EXCEPTION
    WHEN DBMS_LOB.NOEXIST_DIRECTORY THEN
        RAISE_APPLICATION_ERROR(-20000, 'EL DIRECTORIO NO EXISTE');
END;
/