-- EMPTY_CLOB
-- EMPTY_BLOB

-- LOS LOBS SON PUNTEROS A UN ESPACIO DONDE ESTARÁ EL CONTENIDO

INSERT INTO PRU_LOB VALUES (3, 'JUAN', EMPTY_CLOB(), EMPTY_BLOB()); -- SE CREAN LOS PUNTEROS DE LOS LOBS AUNQUE EL CONTENIDO DE ESTOS SEA VACÍO

-- SE RECOMIENDA INICIALIZAR LOS LOBS AUNQUE NO TENGAN CONTENIDO

SELECT * FROM PRU_LOB;

