CREATE TABLE PRU_LOB(
    CODIGO NUMBER,
    NOMBRE VARCHAR2(100),
    DATOS CLOB
);

DESC PRU_LOB;

INSERT INTO PRU_LOB VALUES (1, 'PEDRO', 'AHAHSKAJHSKANNXBDJSHDANSASNASASAASNAMSNASKJAHSKJAHSAJHSKJAHSJAHJSHAJSAHJSA');

SELECT * FROM PRU_LOB;

ALTER TABLE PRU_LOB ADD (FOTO BLOB);

DESC PRU_LOB;

-- INSERT INTO PRU_LOB VALUES (2, 'ROSA', 'AHAHSKAJHSKANNXBDJSHDANSASNASASAASNAMSNASKJAHSKJAHSAJHSKJAHSJAHJSHAJSAHJSA', 'BJHJH'); -- DA ERROR

